version: "3"
services:
  db:
    image: postgres
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - '127.0.0.1:5432:5432'
  redis:
    image: redis
    ports:
      - '127.0.0.1:6379:6379'
volumes:
  db_volume:
