default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV["DB_POOL"] || ENV["RAILS_MAX_THREADS"] || 5 %>


development:
  <<: *default
  database: ufpi_ticket_development

test:
  <<: *default
  database: ufpi_ticket_test

production:
  <<: *default
  database: accounts_graphql_production
  host: <%= ENV['DATABASE_ADDRESS'] %>
  username: "<%= ENV['DATABASE_USERNAME'] %>"
  password: "<%= ENV['DATABASE_PASSWORD'] %>"
